---
title: "loop functions"
author: "sharan"
date: '2022-06-10'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# lappy()

```{r}
lapply
x <- list(a = 1:6 , b = rnorm(6,2,1))
lapply(x, mean)

```

```{r}
x <- 1:4
lapply(x,runif)

x <- list(a = matrix(1:4,2,2), b = matrix(1:6,3,2))
x
lapply(x, function(elt){elt[,1]})
```
```{r}
x <- list(a = 1:4, b = rnorm(10,1,1),c = rbinom(n = 100,size = 10,prob = 0.5), d = rnorm(10,3))
lapply(x,mean)
sapply(x, mean)
```
# split()
```{r}
str(split)
set.seed(1312)
x <- c(rnorm(10), runif(10), rnorm(10,1))
f <- gl(3,10)
split(x,f)
sapply(split(x,f),mean)
```
#Splitting a data Frame

```{r}
library(datasets)
head(airquality)
s <- split(airquality, airquality$Month)
str(s)
sapply(s, function(x){colMeans(x[,c("Ozone","Solar.R","Wind")],na.rm = T)})
```

# tapply()
```{r}
str(tapply)
x <- c(rnorm(10),runif(10),rnorm(10,1))
f <- gl(3,10)
tapply(x,f,mean)
```
# apply()
```{r}
set.seed(1312)
x <- matrix(rnorm(9),3,3)
x
print("colmean")
apply(x,2,mean)
print("rowsum")
apply(x,1,sum)
print("colsum")
apply(x,2,sum)
print("quantile")
apply(x,2,quantile, probs = c(.25,.75))
```
# mapply()
```{r}
mapply(rep,1:5,3:7)
```
# vectorizing a function
```{r}
set.seed(1312)
 sqsum <- function(mu, sigma, x){
   sum((x-mu)/(sigma^2))
 }
x <- rnorm(100)
sqsum(1:10,1:10,x)
print("using mapply")
mapply(sqsum,1:10,1:10,MoreArgs = list(x=x))
print("Vectorize function use")
vum <- Vectorize(sqsum,c("mu","sigma"))
vum(1:10,1:10,x)
```
